### ISSUE TITLE
OpenGL support will not be compiled in

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#102]
By executing "sudo apt-get install freeglut3-dev" to get the required libraries, then enabling the ENABLE_OPENGL CMake configuration flag during compilation, the following message is shown.

OpenGL support will not be compiled in

It seems OpenGL compiling is not set.
Please let me knouw how to use OpenGL compiling.

**Comment by AmmarkoV** [comment]
Dear Ishihara

Issuing : 

```
cd build
cmake ENABLE_OPENGL=1 ..
make 
```

should switch on the OpenGL renderer giving you a 

"  OpenGL code found and will be used.. " message 

However keep in mind that  MocapNET has a new [plugin/script](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/blender/blender_mocapnet.py) for the [Blender](https://www.blender.org/) 3D editor that when combined with [MPFB2](http://static.makehumancommunity.org/mpfb.html) (the MakeHuman addon for Blender) can make 3D animations using custom skinned humans with the output BVH files of MocapNET with a few clicks.  

You can click and watch the video below  for more information
[![YouTube Link](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/blenderytb.png)](https://www.youtube.com/watch?v=ooLRUS5j4AI)

The 3D output is vastly superior to my 3D renderer ( it can be raytraced etc) and it is less of a hassle in terms of dependencies code maintenance etc.
