### ISSUE TITLE
The BVHGUI2 genetats nothing

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#104]
I run the following command to use The BVHGUI2.
```
./BVHGUI2 --opengl
```
But it generats nothing as the below image.

![Screenshot from 2023-07-25 04-49-07](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/23301778/bc6ed1df-b473-4c7f-8d4b-0efd95416ebb)

**Comment by AmmarkoV** [comment]
Seeing nothing when invoking the --opengl view means that the [opengl code](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/visualization/opengl.cpp#L5) has been compiled without the appropriate CMake flag 

Issuing : 

```
cd build
cmake ENABLE_OPENGL=1 ..
make 
```
should correct this problem
