### ISSUE TITLE
Connecting to cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80... 

### ISSUE THREAD

**Issue by jaswu51** [FORTH-ModelBasedTracker/MocapNET#106]
Resolving cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)... 139.91.185.61
Connecting to cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80... failed: Connection timed out.
Retrying.

**Comment by AmmarkoV** [comment]
Hello this is a duplicate of -> https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/96
The problem exists on the network operation center of FORTH
If you git pull the code has been updated to currently [get the pretrained models from a google drive](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L121)

**Comment by AmmarkoV** [comment]
Also mirroring the groundtruth BVH dataset files this issue has been fixed by hosting the files on google instead of cvrlcode.ics.forth.gr
