### ISSUE TITLE
Error: neuralNetworkLoad could not find a tf2/tf1 model to load..

### ISSUE THREAD

**Issue by yjfyqszs** [FORTH-ModelBasedTracker/MocapNET#108]
Hi，I have ran this code on Windows subsystem for Linux(Ubuntu 18.04). I used the brach "mnet3", and successfully generated the "2dJoints_mediapipe.csv" by running `python3 src/python/mediapipe/mediapipeHolistic2CSV.py --from shuffle.webm -o tester`.
But when running `./MocapNET2CSV --from tester-mpdata/2dJoints_mediapipe.csv --show 3 --hands`, there are some errors showing in the following image, how can i fix it?
<img width="837" alt="error" src="https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/17742602/1c0e90f8-a68e-4a3e-a237-ccd0b5e2c7f8">

**Comment by AmmarkoV** [comment]
Hello, this is a problem with CUDA and libcudart.so.10 that is probably not available in WSL 
While running the ./initialize.sh , when asked you should have chosen the non GPU version of tensorflow!

The next version of MocapNET (mnet4 branch) has been rewritten from scratch in Python to make it more portable across systems with different OSes / GPUs   etc.!

You can actually try it with a few clicks  in Google Collab : [![Open MocapNET v4 In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/FORTH-ModelBasedTracker/MocapNET/blob/mnet4/mocapnet4.ipynb)

**Comment by yjfyqszs** [comment]
> Hello, this is a problem with CUDA and libcudart.so.10 that is probably not available in WSL While running the ./initialize.sh , when asked you should have chosen the non GPU version of tensorflow!
> 
> The next version of MocapNET (mnet4 branch) has been rewritten from scratch in Python to make it more portable across systems with different OSes / GPUs etc.!
> 
> You can actually try it with a few clicks in Google Collab : [![Open MocapNET v4 In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/FORTH-ModelBasedTracker/MocapNET/blob/mnet4/mocapnet4.ipynb)

Thanks! I have successfully ran mnet4 both on Colab and my computer.
