### ISSUE TITLE
openpose error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#112]
When I run openpose.bin, the following error occurred.

```
$ ./openpose/build/examples/openpose/openpose.bin -number_people_max 1 --hand --write_json ./output -video ./clip2.mp4
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Prototxt file not found: models/hand/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the root directory (i.e., where the `model` folder is located, but do not move the `model` folder!). E.g.,
		Right example for the Windows portable binary: `cd {OpenPose_root_path}; bin/openpose.exe`
		Wrong example for the Windows portable binary: `cd {OpenPose_root_path}/bin; openpose.exe`
	3. Using paths with spaces.

Coming from:
- /home/dl/Mocap/MocapNET/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():61
- /home/dl/Mocap/MocapNET/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():97
- /home/dl/Mocap/MocapNET/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1221
- /home/dl/Mocap/MocapNET/openpose/include/openpose/wrapper/wrapper.hpp:exec():424
 ```
Please let me know how to fix it.

**Comment by AmmarkoV** [comment]
Hello unfortunately this error is from the OpenPose library and it's installation so I don't know the exact issue and can't help fixing it! The error message states that it cannot find the OpenPose model file so this means a problem during installation, or with the current directory ?

**Comment by justinjohn0306** [comment]
> When I run openpose.bin, the following error occurred.
> 
> ```
> $ ./openpose/build/examples/openpose/openpose.bin -number_people_max 1 --hand --write_json ./output -video ./clip2.mp4
> Starting OpenPose demo...
> Configuring OpenPose...
> Starting thread(s)...
> Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
> 
> Error:
> Prototxt file not found: models/hand/pose_deploy.prototxt.
> Possible causes:
> 	1. Not downloading the OpenPose trained models.
> 	2. Not running OpenPose from the root directory (i.e., where the `model` folder is located, but do not move the `model` folder!). E.g.,
> 		Right example for the Windows portable binary: `cd {OpenPose_root_path}; bin/openpose.exe`
> 		Wrong example for the Windows portable binary: `cd {OpenPose_root_path}/bin; openpose.exe`
> 	3. Using paths with spaces.
> 
> Coming from:
> - /home/dl/Mocap/MocapNET/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():61
> - /home/dl/Mocap/MocapNET/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():97
> - /home/dl/Mocap/MocapNET/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1221
> - /home/dl/Mocap/MocapNET/openpose/include/openpose/wrapper/wrapper.hpp:exec():424
> ```
> 
> Please let me know how to fix it.

since the openpose servers are down, you can manually download the models from here and then rebuild the modules: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
