### ISSUE TITLE
a skinned mesh doesn't appear

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#113]
According to your instruction, a skinned mesh is shown as the folloing command.

```
./MocapNET2LiveWebcamDemo --from shuffle.webm --openpose --gestures --frames 375
```

like,
![Screenshot from 2023-10-19 15-10-22](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/23301778/e74b0bed-c2bc-4ff8-b5ae-ed4c810a4783)

But, just the following figure is shown.
![Screenshot from 2023-10-19 15-09-45](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/23301778/1e2a9de6-7bb5-4b80-ab89-8db370db4f3b)

**Comment by AmmarkoV** [comment]
You need to :  
1) sudo apt-get install freeglut3-dev
2)  Enable the ENABLE_OPENGL CMake configuration flag during compilation 
3) Using the --opengl flag when running the MocapNET2LiveWebcamDemo  

Your example call  from
```
./MocapNET2LiveWebcamDemo --from shuffle.webm --openpose --gestures --frames 375
```

should become

```
./MocapNET2LiveWebcamDemo --from shuffle.webm --openpose --opengl --gestures --frames 375
```

Please also note that this hardcoded visualization has been superseeded by Blender/Make human for blender 
[![Watch the video](https://img.youtube.com/vi/ooLRUS5j4AI/maxresdefault.jpg)](https://youtu.be/ooLRUS5j4AI) 

and that the recent version of MocapNET can be also run using Google Collab :  
https://colab.research.google.com/github/FORTH-ModelBasedTracker/MocapNET/blob/mnet4/mocapnet4.ipynb
