### ISSUE TITLE
[ 21%] Building CXX object src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/bvh.cpp.o

### ISSUE THREAD

**Issue by simon-eda** [FORTH-ModelBasedTracker/MocapNET#12]
Hi, 
i always get following error, when i initialize MocapNET. 
your help to solve the issue would be great. 

Thanks,
Simon 

[ 21%] Building CXX object src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/bvh.cpp.o
/content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp: In function ‘std::vector<std::vector<float> > convertBVHFrameTo2DPoints(std::vector<float>, unsigned int, unsigned int)’:
/content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp:272:60: error: too few arguments to function ‘int bvh_loadTransformForMotionBuffer(BVH_MotionCapture*, float*, BVH_Transform*, unsigned int)’
                                                            )
                                                            ^
In file included from /content/MocapNET/src/MocapNET1/MocapNETLib/../../../dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/calculate/bvh_project.h:5:0,
                 from /content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp:7:
/content/MocapNET/src/MocapNET1/MocapNETLib/../../../dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/calculate/bvh_transform.h:113:5: note: declared here
 int bvh_loadTransformForMotionBuffer(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp: In function ‘std::vector<float> convertBVHFrameToFlat3DPoints(std::vector<float>, unsigned int, unsigned int)’:
/content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp:353:60: error: too few arguments to function ‘int bvh_loadTransformForMotionBuffer(BVH_MotionCapture*, float*, BVH_Transform*, unsigned int)’
                                                            )
                                                            ^
In file included from /content/MocapNET/src/MocapNET1/MocapNETLib/../../../dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/calculate/bvh_project.h:5:0,
                 from /content/MocapNET/src/MocapNET1/MocapNETLib/bvh.cpp:7:
/content/MocapNET/src/MocapNET1/MocapNETLib/../../../dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/calculate/bvh_transform.h:113:5: note: declared here
 int bvh_loadTransformForMotionBuffer(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/build.make:400: recipe for target 'src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/bvh.cpp.o' failed
make[2]: *** [src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/bvh.cpp.o] Error 1
CMakeFiles/Makefile2:200: recipe for target 'src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/all' failed
make[1]: *** [src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AmmarkoV** [comment]
Hello, I fixed the problem, I made a change on an other repository and forgot to commit here as well.. 
At least the BVH code works a little faster with it :) 
If you git pull latest version it should now compile properly..!
https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/5314bd500b78ca62dd36ba5b95c3407cc34fdfa2

**Comment by AmmarkoV** [comment]
This is fixed so closing issue
