### ISSUE TITLE
can’t work ./MocapNET2LiveWebcamDemo There was a problem with the file initialize.sh

### ISSUE THREAD

**Issue by notbugnotwork** [FORTH-ModelBasedTracker/MocapNET#121]
sudo ./MocapNET2LiveWebcamDemo --from /mnt/c/Users/Administrator/Downloads/test.mp4 --openpose
2024-06-10 12:00:00.529398: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-06-10 12:00:00.529467: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
CPU :  Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU :
Trying to open source (/mnt/c/Users/Administrator/Downloads/test.mp4)
Using BVH codebase version 0.74
buildOpenGLProjectionForIntrinsics: img(720x1280) fx 582.18, fy 582.53, cx 360.00, cy 640.00
Fast BVH parser revealed 212 joints / 0 motion fields

Number of Values Per Frame: 498
Allocating 1992 bytes of memory to hold BVH motions
Frames: 1(1) / Frame Time : 0.0400
BVH subsystem initialized using dataset/headerWithHeadAndOneMotion.bvh that contains 1 frames ( 498 motions each )
Initializing IK code..
Body Problem :

The IK problem "Body" we want to solve
is ultimately divided into 8 kinematic chains
Chain 0 has 20 parts : jID(hip/0)->mID(0 to 2) jID(hip/0)->mID(3 to 5) jID(neck1/4)->EndEffector jID(head/5)->EndEffector jID(EndSite_eye.l/71)->EndEffector jID(EndSite_eye.r/79)->EndEffector jID(__temporalis02.l/94)->EndEffector jID(__temporalis02.r/99)->EndEffector jID(rShldr/105)->EndEffector jID(rForeArm/106)->EndEffector jID(rHand/107)->EndEffector jID(lShldr/136)->EndEffector jID(lForeArm/137)->EndEffector jID(lHand/138)->EndEffector jID(rThigh/167)->EndEffector jID(rShin/168)->EndEffector jID(rFoot/169)->EndEffector jID(lThigh/190)->EndEffector jID(lShin/191)->EndEffector jID(lFoot/192)->EndEffector
Chain 1 has 6 parts : jID(neck1/4)->mID(15 to 17) jID(head/5)->EndEffector jID(EndSite_eye.l/71)->EndEffector jID(EndSite_eye.r/79)->EndEffector jID(__temporalis02.l/94)->EndEffector jID(__temporalis02.r/99)->EndEffector
Chain 2 has 3 parts : jID(rShldr/105)->mID(237 to 239) jID(rForeArm/106)->mID(240 to 242) jID(rHand/107)->EndEffector
Chain 3 has 3 parts : jID(lShldr/136)->mID(315 to 317) jID(lForeArm/137)->mID(318 to 320) jID(lHand/138)->EndEffector
Chain 4 has 5 parts : jID(rThigh/167)->mID(393 to 395) jID(rShin/168)->mID(396 to 398) jID(rFoot/169)->mID(399 to 401) jID(EndSite_toe1-2.R/172)->EndEffector jID(EndSite_toe5-3.R/188)->EndEffector
Chain 5 has 3 parts : jID(rFoot/169)->mID(399 to 401) jID(EndSite_toe1-2.R/172)->EndEffector jID(EndSite_toe5-3.R/188)->EndEffector
Chain 6 has 5 parts : jID(lThigh/190)->mID(447 to 449) jID(lShin/191)->mID(450 to 452) jID(lFoot/192)->mID(453 to 455) jID(EndSite_toe1-2.L/195)->EndEffector jID(EndSite_toe5-3.L/211)->EndEffector
Chain 7 has 3 parts : jID(lFoot/192)->mID(453 to 455) jID(EndSite_toe1-2.L/195)->EndEffector jID(EndSite_toe5-3.L/211)->EndEffector
End of problem "Body"
BVH code initalization successfull..
Trying to set thread realtime prio = 99
SCHED_FIFO OK
Thread priority is now 99
Graph dataset/combinedModel/openpose_model.pb could not be found

i don't konw how to fix it ,it seems like the MocapNET2LiveWebcamDemo is binary file,i can't figure out

**Comment by lf-cardoso** [comment]
I faced the same problem and found that for some reason, initialize.sh couldn't download and extract the weights.

I resolved it by manually downloading and extracting the allInOneMNET2RedistMirrorICPR2020.zip (drive.google.com/u/3/uc?id=1GtmPWOpf3MzhqhqegaC8cS3_m3Drp6y3&export=download&confirm=yes) and CMUPlusHeadMotionCapture.zip (drive.google.com/u/3/uc?id=1Zt-MycqhMylfBUqgmW9sLBclNNxoNGqV&export=download&confirm=yes) files. Then, I added the MotionCapture directory from the CMUPlusHeadMotionCapture.zip file to the dataset directory.

**Comment by notbugnotwork** [comment]
When I use wget --no-check-certificate to download a file manually, it works without any issues. However, when I replace wget with wget --no-check-certificate in the script and rerun it, the script still fails to download the files. Almost all the parts of the script that involve wget are unable to download the files.

**Comment by notbugnotwork** [comment]
> 我遇到了同样的问题，发现由于某种原因，initialize.sh 无法下载和提取权重。
> 
> 我通过手动下载并提取 allInOneMNET2RedistMirrorICPR2020.zip (drive.google.com/u/3/uc?id=1GtmPWOpf3MzhqhqegaC8cS3_m3Drp6y3&export=download&confirm=yes) 和 CMUPlusHeadMotionCapture.zip (drive.google.com/u/3/uc?id=1Zt-MycqhMylfBUqgmW9sLBclNNxoNGqV&export=download&confirm=yes) 文件解决了这个问题。然后，我将 CMUPlusHeadMotionCapture.zip 文件中的 MotionCapture 目录添加到数据集目录中。

This issue might require someone knowledgeable about scripts to resolve.

**Comment by AmmarkoV** [comment]
This is a server problem, probably related to https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/106

I will contact the network administrators of FORTH to try and solve this..

**Comment by AmmarkoV** [comment]
Hosting problems are fixed (until FORTH admins change something again :) )
