### ISSUE TITLE
Doesn't work. 

### ISSUE THREAD

**Issue by Vidyut** [FORTH-ModelBasedTracker/MocapNET#122]
The script stalls at trying to fetch  http://cvrlcode.ics.forth.gr/web_share/mocapnet//shuffle.webm

**Comment by AmmarkoV** [comment]
Sorry about that, This is a hosting problem with the network administrators of FORTH 
Probably related to https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/106
I will try to contact them to fix this

**Comment by AmmarkoV** [comment]
@Vidyut  Does this link work to you ?

http://ammar.gr/datasets/shuffle.webm

**Comment by Vidyut** [comment]
Wow. That was fast. I sort of figured my way around using the colab commands. It was just a video file, so I guessed it wasn't crucial.

Unfortunately I'm on the newly released Ubuntu 24.04 and I've got ... issues with the GPU. TF-TRT Warning: Could not find TensorRT

So I guess I'm stuck until updates happen or something.

(Warning: I'm completely ignorant and basically a champion copy-paster. Half the time I don't know what I'm doing)

Maybe I'll just use the colab. I have it open anyway to copy commands from. lol

**Comment by AmmarkoV** [comment]
Yes I guess just use the [colab](https://colab.research.google.com/github/FORTH-ModelBasedTracker/MocapNET/blob/mnet4/mocapnet4.ipynb)  the code (on my part) should be able to compile on Ubuntu 24.04, but [finding the correct combination of Tensorflow/CUDA](https://www.tensorflow.org/install/source#linux) etc is a pretty hard exercise , and the same thing goes for building a custom version of tensorflow. I have a [script to guide through the process](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/tensorflow2Build.sh), however from one TF version to another all sorts of things break and change.. 

In any case, sorry for the trouble, I hope you can use the collab version without problems..!

**Comment by Vidyut** [comment]
Yes, the colab works. Now to figure out the generation. I got the csv, but when I applied it, it looked nothing like the video. I think I used the wrong script or something face/body, so the wrong stuff got animated. Stuck with something right now, but will figure it out soon, and if I find something useful that prevents more newbies making the same mistakes, will share here.

**Comment by AmmarkoV** [comment]
Hosting problems are fixed (until FORTH admins change something again :) )
