### ISSUE TITLE
File and path errors displayed as  Could not find COCO 2D skeleton

### ISSUE THREAD

**Issue by delebash** [FORTH-ModelBasedTracker/MocapNET#17]
I ran into this when I did a webcam output from openpose.  With the webcam output there is no label so when I ran .`/MocapNETJSON --from openpose-input  --seriallength 12 --size 1920 1080` note without --label and that is when I get the error.  Also if I point to a wrong path by mistake the error above is also displayed.  Suggestion would be to make file path not found errors as just that and not the above error.

Thanks.
Love this software just what poor me has been looking for :)

**Comment by AmmarkoV** [comment]
So to make it clear, you would prefer if an error occured when the label is missing to have a specific warning about that, and when the path is correct and there is a label wrong to have a specific warning about that. 
Instead of the generic, did not find the skeleton ? 

( I am trying to understand what I need to fix :) )

**Comment by delebash** [comment]
Yes that is correct.  If I know it is a path error and not something else I can easily fix that.  Any time any error is related to path it would be nice to know.  As far as error handling goes any time you can be specific about the error thrown you should.

Thank you very much!
Dan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AmmarkoV** [comment]
There is a [new tool to dump datasets](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/dump_and_process_video.sh) and CSV files make file and path errors obsolete..!
