### ISSUE TITLE
Is it possible to use this without a webcam?

### ISSUE THREAD

**Issue by omegarunner1** [FORTH-ModelBasedTracker/MocapNET#21]
Hello, I just found today and I've been looking for documentation on how to use what's available before I do some tinkering and one thing I found here is that it seems to require a webcam. I do not have a webcam but I have a smartphone I can film myself with. Is it possible to use this with prerecorded videos in any capacity? If it is, could it be explained how? And, if not, could such a thing be added later?

**Comment by AmmarkoV** [comment]
Yes of course, you can use the MocapNETLiveWebcamDemo utility with a video file..! I suppose the WebcamDemo in the executable name is a little misleading :) but you can use any OpenCV compatible source capture including :

- video file (eg. video.avi)
- image sequence (eg. img_%02d.jpg, which will read samples like img_00.jpg, img_01.jpg, img_02.jpg, ...)
- URL of video stream (eg. protocol://host:port/script_name?script_params|auth)
- GStreamer pipeline string in gst-launch tool format in case if GStreamer is used as backend Note that each video stream or IP camera feed has its own URL scheme. 
 as seen in [OpenCV documentation](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html)

The initialization script automatically downloads the "shuffle.webm" video that you can test using :

`./MocapNETLiveWebcamDemo --from shuffle.webm 
`

reading the README step by step it also mentions this..!

**Comment by AmmarkoV** [comment]
Also as I already discussed with some other guys in this issues section keep in mind that I am waiting for some peer reviews, I have ~1 year of work that is waiting to get committed here that will be a pretty substantial improvement in pose estimation quality! 
 
a preview of the next version, i.e. 
[From this source video](https://www.youtube.com/watch?v=LgcP47DlChU) to [this BVH](http://ammar.gr/mocapnet/mnet2/newversion.webm) 

The current version here is not too bad but the new version is definitely better, the good thing is that the BVH files are exactly the same so it will be easy to upgrade once it lands here..

**Comment by AmmarkoV** [comment]
Closing this issue as it is possible to use MocapNET without a webcam! :)
