### ISSUE TITLE
2D-3D mapping part

### ISSUE THREAD

**Issue by HilmiiKumdakci** [FORTH-ModelBasedTracker/MocapNET#22]
Hi,

Can I learn where the mapping part is where 2D-3D conversion is performed.

Thanks

**Comment by AmmarkoV** [comment]
Hello

I am not sure that I understand your question. There is no clear "mapping" part.  MocapNET is an end-to-end neural network 3D pose estimator. The neural network has been trained to get NSDM matrices as Input and directly output BVH output.


![image](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/figureA.png)

![image](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/figureB.png)



The [MNET3Classes](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/mocapnet.cpp#L481) function receives a populated std::vector<float> mnetInput with the input packed in a [NSDM matrix ](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/nsdm.cpp#L22) and will give you back a vector that is ready to be appended to a BVH file.

**Comment by AmmarkoV** [comment]
I suppose the question is answered so I am closing the issue!
