### ISSUE TITLE
why use './initialize.sh' appear  './MocapNET-master/src/MocapNETServerHTTP does not concatin a CMakeLists.txt file'

### ISSUE THREAD

**Issue by FrankYoungchen** [FORTH-ModelBasedTracker/MocapNET#26]
hi,bro
when I why use './initialize.sh' ,
it will appear CMake Error at CmakeLists.txt:273(add_subdirectory):
The source directory
    ./MocapNET-master/src/MocapNETServerHTTP 
does not concatin a CMakeLists.txt file

make: *** No targets specified and no makefile found. Stop

**Comment by AmmarkoV** [comment]
Hello! 
I will correct this now,
this HTTP stuff was for some experiments using a remote server but it is really not needed and just needless complexity that has been removed..!

**Comment by AmmarkoV** [comment]
If you git pull and try to rebuild it should build correctly now..!

**Comment by FrankYoungchen** [comment]
> If you git pull and try to rebuild it should build correctly now..!

ok，thx～

**Comment by FrankYoungchen** [comment]
hi,bro,I have git pull, and `./initialize.sh, `but it appear error:
```
Scanning dependencies of target MocapNETLib

[ 10%] Building CXX object src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/mocapnet.cpp.o

In file included from /home/chenyukun/cyk/pose/MocapNET/src/MocapNET1/MocapNETLib/mocapnet.cpp:1:0:

/home/chenyukun/cyk/pose/MocapNET/src/MocapNET1/MocapNETLib/../../Tensorflow/tf_utils.hpp:32:59: fatal error: tensorflow/c/c_api.h: No such file or directory

compilation terminated.

src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/build.make:62: recipe for target 'src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/mocapnet.cpp.o' failed

make[2]: *** [src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/mocapnet.cpp.o] Error 1

CMakeFiles/Makefile2:271: recipe for target 'src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/all' failed

make[1]: *** [src/MocapNET1/MocapNETLib/CMakeFiles/MocapNETLib.dir/all] Error 2

Makefile:83: recipe for target 'all' failed

make: *** [all] Error 2
```
So what should I do？

**Comment by FrankYoungchen** [comment]
It will be OK after I fix tensorflow edition

**Comment by AmmarkoV** [comment]
If you look at the initialize.sh script from lines [169](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L169) to [216](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L216) it downloads tensorflow C-API 1.1x and uncompresses it in dependencies/libtensorflow/ 

This

```
fatal error: tensorflow/c/c_api.h: No such file or directory
compilation terminated.

```

error means that the libtensorflow stuff it is not there..!

![2020-09-10-104029_3840x1080_scrot](https://user-images.githubusercontent.com/97630/92696135-20b7b680-f352-11ea-89ed-58e623dbbf31.png)


In case something interrupted your download of the tensorflow dependencies/libtensorflow-gpu-linux-x86_64-1.14.0.tar.gz try deleting the "dependencies/libtensorflow-gpu-linux-x86_64-1.14.0.tar.gz" file as well as the "dependencies/libtensorflow/" directory and rerunning the ./initialize.sh script so you will get a fresh one.

**Comment by AmmarkoV** [comment]
I have corrected the issue so I am closing this ticket.!
In case the tensorflow issue persists [ or you have another problem ] feel free to open a new issue that has it as the title ( so someone else experiencing the problem will find it )
