### ISSUE TITLE
CMake error Jetson NX

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [FORTH-ModelBasedTracker/MocapNET#29]
Hi,
I am having the following cmake error. Can you kindly help with the error if possible?
I am using Jetson Xavier NX.

Thanks

`[ 38%] Linking CXX shared library ../../../../libMocapNETLib2.so
../../../../dependencies/libtensorflow/lib/libtensorflow.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/build.make:1094: recipe for target '../libMocapNETLib2.so' failed
make[2]: *** [../libMocapNETLib2.so] Error 1
CMakeFiles/Makefile2:475: recipe for target 'src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/all' failed
make[1]: *** [src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by AmmarkoV** [comment]
Hello,
This is the same issue as https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/20
The problem you are facing is that [the libtensorflow.so downloaded by the initialize.sh script](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L152) is compiled for x64 CPUs and not ARM/Jetson machines.. 

You need to find/build  tensorflow 1.1x for your platform and replace the dependencies/libtensorflow dir with  it
https://forums.developer.nvidia.com/t/tensorflow-libs-for-c-c-integration-on-jetson-nano/71706

**Comment by AmmarkoV** [comment]
Tensorflow 2.3+ is now also compatible with MocapNET  so it is also an option if you can find a build for Jetson NX

**Comment by AmmarkoV** [comment]
@AswinkarthikeyenAK  also consider [this script](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/tensorflowBuild.sh) that might help you build tensorflow on your Jetson device..

**Comment by AmmarkoV** [comment]
I "found" a Jetson TX2 so I will try building there when I get the chance

**Comment by AmmarkoV** [comment]
Hello, it appears https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/70 that there is a libtensorflow for Jetson devices! here ! 
So using it you can build MocapNET for Jetson https://github.com/nevillerichards/tensorflow/releases
