### ISSUE TITLE
MocapNET2CSV demo not starting up

### ISSUE THREAD

**Issue by beemsoft** [FORTH-ModelBasedTracker/MocapNET#31]
Hi Ammar,
The MocapNET2CSV demo doesn't seem to work.

When I run with:
`./MocapNET2CSV --from sample.csv --visualize --delay 30`

I'm getting a message "TODO: do face associations.."

**Comment by AmmarkoV** [comment]
The CSV file you tried running was a left-over from the MocapNET1 release so I updated it to a new one ( basically the  difference is that new csv files have prefix columns to accomodate multiple persons [ multiple persons are not yet supported btw ]  )

Please try git pulling and running your command again..

```
./MocapNET2CSV --from dataset/sample.csv  --delay 30
```

If you want a "bigger" dataset you can [try this one ~1.5GB](http://ammar.gr/datasets/sven.mp4-data.tar.gz)   -> 

```
mkdir frames
cd frames
wget http://ammar.gr/datasets/sven.mp4-data.tar.gz
tar -xf sven.mp4-data.tar.gz
cd ..

./MocapNET2CSV --from frames/sven.mp4-data/2dJoints_v1.4.csv --show 3  --mt --opengl
```

**Comment by AmmarkoV** [comment]
I am closing this since I am 100% sure that I updated the sample file and fixed the issue! 
```
./MocapNET2CSV --from dataset/sample.csv --visualize --delay 30
```
now works
