### ISSUE TITLE
could not create cudnn handle:CUDNN_STATUS_INITERNAL_ERROR

### ISSUE THREAD

**Issue by FrankYoungchen** [FORTH-ModelBasedTracker/MocapNET#32]
Hi,bro
After  './update.sh' and './initialize.sh', after caching model,it will be 
`'E tensorflow /stream_execuor/cuda/cuda_dnn.cc::329',could not create cudnn handle:CUDNN_STATUS_INTERNAL_ERROR'`

**Comment by FrankYoungchen** [comment]
The last version did not have this ERROR

**Comment by FrankYoungchen** [comment]
![Uploading WeChata1b38d9ed75cb8bb820cb19ec873b24d.png…]()

**Comment by FrankYoungchen** [comment]
The previous version did not have this ERROR

**Comment by AmmarkoV** [comment]
Well new version loads 3x as many networks so this is probably an "out-of-memory" error ?
What is you RAM size / GPU RAM size?

**Comment by FrankYoungchen** [comment]
GPU is nvidia@2080ti

**Comment by AmmarkoV** [comment]
Ok .. :P what tensorflow/cuda version do you have ? This may then be the fact that tensorflow 1.14 build with CUDA10 in mind might not be forward compatible with such a new GPU ? 

Also can you supply the whole output of the application, maybe there is another hint somewhere

**Comment by FrankYoungchen** [comment]
tensorflow 1.14、cuda 10、cudnn 7.4.2，wait me moment，I will print log

**Comment by AmmarkoV** [comment]
Ok also maybe test if running with --cpu to force CPU only mode works..

**Comment by FrankYoungchen** [comment]
Because the company process log can only be given to you tomorrow，
Whether it is cpu or gpu，it will appear `'GLib-GObject-CRITICAL **:g_object_unref:assertion 'G_IS_OBJECT(object)'failed'`

**Comment by FrankYoungchen** [comment]
[log.txt](https://github.com/FORTH-ModelBasedTracker/MocapNET/files/5384061/log.txt)
hi,it is log,thx!!!

**Comment by AmmarkoV** [comment]
The log reveals that the problem is actually the video file..!
```
Trying to open source (shuffle.webm) 
[matroska,webm @ 0x16bd740] Read error
```

```
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Broken frame.. 
Too many broken frames.. 
```
A thing we can try is a different video file
go inside the MocapNET directory and do
```
wget http://ammar.gr/mocapnet/sven.mp4
./MocapNET2LiveWebcamDemo --from sven.mp4 --show 3 --cpu
```
Does it work? If not what is the new output log ?

**Comment by FrankYoungchen** [comment]
Hello，it works in CPU，but not in GPU，Maybe my CUDA and Cudnn has problem
Here is log in GPU
[log.txt](https://github.com/FORTH-ModelBasedTracker/MocapNET/files/5389028/log.txt)

**Comment by AmmarkoV** [comment]
If it works in CPU then for sure the problem is your CUDA and CUDNN, I have changed the initialize script and now tensorflow 2.x is supported so try installing [CUDA10](https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu) , [cudnn-10.0-linux-x64-v7.6.5.32.tgz](https://developer.nvidia.com/cudnn)  and the  [Tensorflow 2.3.1](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.3.1.tar.gz) replacing  the current tensorflow 2.3.1 stuff in dependencies/libtensorflow

Running the initialize.sh script now defaults to this 2.3.1 tensorflow version

**Comment by FrankYoungchen** [comment]
yes，sir～
