### ISSUE TITLE
OpenGL error after getOpenGLColor()

### ISSUE THREAD

**Issue by FrankYoungchen** [FORTH-ModelBasedTracker/MocapNET#36]
Hi,bro,after I solve the Nvidia problem,I run the `--opengl` and I meet a new problem
```
OpenGL Error(1280):.../MocapNET/dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/Rendering/downloadFromRenderer.c 72
An unacceptable value is specified for an enumerated argument.The offending command is ignored and has no other side effect than to set the error flag
```

**Comment by AmmarkoV** [comment]
Can you give me a full log?
This could be multiple things!

**Comment by FrankYoungchen** [comment]
Hi，This is a full log
[log_opengl.txt](https://github.com/FORTH-ModelBasedTracker/MocapNET/files/5400857/log_opengl.txt)

**Comment by AmmarkoV** [comment]
I think the problem might be that for some reason your OpenGL setup does not allow offscreen pbuffer rendering..

One thing you can try is change [opengl.cpp#L31](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/visualization/opengl.cpp#L31)
from 

```
      if (startOpenGLModule(1,"")) //safe
```

to

```
      if (startOpenGLModule(1,"safe")) //safe
```

After recompiling and rerunning  this will spawn an additional OpenGL window which will get rendered and copied to the MocapNET window..

A second thing that might be happening is there is problem with OpenGL3 support(?) 

You can try to change openGLVersion=3; to -> openGLVersion=2; at [opengl_depth_and_color_renderer/src/Library/main.c#L55](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/main.c#L55)

A final thing to try is 
```
sudo apt-get install mesa-utils
glxinfo | grep OpenGL
```

For my development PC I have 

```
glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Quadro P6000/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 450.80.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 450.80.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 450.80.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by FrankYoungchen** [comment]
For my development PC I have

glxinfo | grep OpenGL
```
OpenGL vendor string: Mesa Project
OpenGL renderer string: Software Rasterizer
OpenGL version string: 1.4(2.1 Mesa 10.5.4)
OpenGL exrensions:
```

**Comment by FrankYoungchen** [comment]
you are right，after` glxinfo| grep render`，I find not direct rendering

**Comment by AmmarkoV** [comment]
I am closing this issue since it is not related to MocapNET
