### ISSUE TITLE
train/test source code?

### ISSUE THREAD

**Issue by whitealex95** [FORTH-ModelBasedTracker/MocapNET#39]
Hi, I am trying to reproduce your model on my custom dataset.
Is there any source code on how you trained the model available?
Thanks

**Comment by AmmarkoV** [comment]
Hello, 
The testing code used on the paper requires the [Human3.6M data](http://vision.imar.ro/human3.6m/description.php) 
I have converted it to CSV files for my use, however the H36M license prevents me from re-circulating them so I am afraid I can't help on that end.

If you want to re-create the data that can be used to train a MocapNET-like network, and assuming you selected [Y when asked to download the CMU dataset](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L66)  when you ran the initialize.sh script you can use the [scripts/createRandomizedDataset.sh](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/createRandomizedDataset.sh). This will spawn many CSV files in the dataset/ folder which you can load with python/tensorflow or torch to try learning 2D to BVH.. 

If you want a test dataset based on CMU you can also use the  [scripts/createTestDataset.sh](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/createTestDataset.sh)

**Comment by AmmarkoV** [comment]
Also python code on reading CSV files and comparing stuff is here : 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py#L146
