### ISSUE TITLE
No OpenCV

### ISSUE THREAD

**Issue by omegarunner1** [FORTH-ModelBasedTracker/MocapNET#40]
Hello, I'm attempting to install MocapNET on my system and, after figuring out all the syntax, going through tutorials, and finally running the initialize.sh script, MocapNET is not installing because it's not installing OpenCV. I don't think I'm supposed to do that myself because it's not listed on the front that anything besides the initialize.sh is required but regardless it doesn't seem to be working. Here are my log files.
[CMakeOutput.log](https://github.com/FORTH-ModelBasedTracker/MocapNET/files/5471549/CMakeOutput.log)
[CMakeError.log](https://github.com/FORTH-ModelBasedTracker/MocapNET/files/5471550/CMakeError.log)

**Comment by AmmarkoV** [comment]
The [initialize.sh script will try to install OpenCV](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L21)

so
```
sudo apt-get install build-essential cmake libopencv-dev libjpeg-dev libpng-dev libglew-dev libpthread-stubs0-dev 
```
 is not working for you?

**Comment by omegarunner1** [comment]
That's the weird thing, that particular script seems to work but, when initialize.sh runs, it says there is no OpenCV. I'm not sure what the problem is here, I'm just reporting it.

**Comment by omegarunner1** [comment]
Okay, so an update. I attempted the installs again just now, and it seems to be working just fine. This is something that happens to me quite a bit when I'm dealing with new technology, for whatever reason, I'll attempt something the right way, I do it the right way but it doesn't work, I'll ask for help, then when people get concerned, I try again and it just works magically. I don't know what went wrong here, but maybe the logs will still be useful. I am so sorry about this.

**Comment by AmmarkoV** [comment]
It's ok, happy everything worked out !
The truth is that setting everything up on an arbitrary computer has a lot of points of failures, this is exactly why I opted for an initialize.sh script to try and take care of the various aspects that could go wrong..
The logs show compilation stopped before an OpenCV error, in any case since you managed to get it running I am closing this issue!
