### ISSUE TITLE
The link to the documentation from json file to bvh not working

### ISSUE THREAD

**Issue by fauzan923** [FORTH-ModelBasedTracker/MocapNET#43]
Hi i would like to report that this link, https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/Converters/convertBody25JsonToCSV.cpp#L2 is not working anymore
![Screenshot from 2020-12-04 09-46-26](https://user-images.githubusercontent.com/58033414/101115296-b42d1a80-3615-11eb-9bc5-b7de6efa77d9.png)

**Comment by AmmarkoV** [comment]
Hello, 
This is part of the MocapNET 1 release that has been moved to the mnet1 branch :
The path to the file is now : 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet1/src/Converters/convertBody25JsonToCSV.cpp

in MocapNET2 the converter tool can now also handle hands and face ( thus not only body25 ) and has been renamed to 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/Converters/Openpose/convertOpenPoseJSONToCSV.cpp

Where did you find the link so I may update it on the spot?

**Comment by AmmarkoV** [comment]
I found it and replaced the link with the new one!
Thank you for reporting this issue!
