### ISSUE TITLE
 out.bvh How to import bvhacker，error

### ISSUE THREAD

**Issue by rookiefront** [FORTH-ModelBasedTracker/MocapNET#46]
./MocapNET2LiveWebcamDemo --from shuffle.webm --openpose --show 1 --frames 375

![image](https://user-images.githubusercontent.com/28785644/102340807-ea817700-3fd1-11eb-8420-32de54aec74a.png)

![image](https://user-images.githubusercontent.com/28785644/102340459-878fe000-3fd1-11eb-848c-f5d40126fe75.png)

**Comment by akchain** [comment]
Hello, I got the same issue and how do you fix it? Thanks.

**Comment by jihg88** [comment]
> 

Hello, I got the same issue and how do you fix it? Thanks.
