### ISSUE TITLE
Errors when building Tensorflow in Ubuntu 2020.4 in a Virtual Machine

### ISSUE THREAD

**Issue by Aurosutru** [FORTH-ModelBasedTracker/MocapNET#50]
Hi,

The following errors occur when running ./initialize.sh and Tensorflow is building.  The same errors occur for Ver. 1.x and 2.x.

         Do you want to use Tensorflow 1.x instead of 2.x ? 
The project is compatible with both but if you have an older GPU it might be better for you 
to stick with Tensorflow 1.x 

 (Y/N)?n
Selected Tensorflow version cpu/2.3.1
Found a local tensorflow installation, not altering anything
./initialize.sh: line 285: git: command not found
./initialize.sh: line 286: cd: RGBDAcquisition: No such file or directory
mkdir: cannot create directory ‘build’: File exists
CMake Error: The source directory "/home/tm/Downloads/MocapNET-master/dependencies" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./initialize.sh: line 292: cd: ../opengl_acquisition_shared_library/opengl_depth_and_color_renderer: No such file or directory
mkdir: cannot create directory ‘build’: File exists
CMake Error: The source directory "/home/tm/Downloads/MocapNET-master/dependencies/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Now to try and build MocapNET..
Build directory already exists, but since the initialize.sh script was called 
this means the user wants to also initialize the build directory, so doing this
to prevent problems like https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/19
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SSE2 detected and will be used..
Using locally found libtensorflow v1 C-API
OpenGL support will not be compiled in
-- Could NOT find OpenCV (missing: OpenCV_DIR)
-- Found OpenCV: /usr (found version "4.2.0") 
OpenCV code found and will be used..
/usr/lib/x86_64-linux-gnu/cmake/opencv4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tm/Downloads/MocapNET-master/build
Scanning dependencies of target OpenCVTest
[  1%] Building CXX object src/Webcam/CMakeFiles/OpenCVTest.dir/webcam.cpp.o
[  2%] Linking CXX executable ../../../OpenCVTest
[  2%] Built target OpenCVTest
Scanning dependencies of target MocapNETLib2
[  3%] Building CXX object src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/core/core.cpp.o
[  4%] Building CXX object src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/core/singleThreaded.cpp.o
[  5%] Building CXX object src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/core/multiThreaded.cpp.o
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp: In function ‘void* mocapNETWorkerThread(void*)’:
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:9:52: error: invalid use of incomplete type ‘struct mocapNETWorkerThread(void*)::threadContext’
    9 |   fprintf(stderr,"MNET Thread-%u: Started..!\n",ptr->threadID);
      |                                                    ^~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:8:10: note: forward declaration of ‘struct mocapNETWorkerThread(void*)::threadContext’
    8 |   struct threadContext * ptr = (struct threadContext *) arg;
      |          ^~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:10:73: error: invalid use of incomplete type ‘struct mocapNETWorkerThread(void*)::threadContext’
   10 | ocapNETContext * contextArray = (struct mocapNETContext *) ptr->argumentToPass;
      |                                                               ^~

/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:8:10: note: forward declaration of ‘struct mocapNETWorkerThread(void*)::threadContext’
    8 |   struct threadContext * ptr = (struct threadContext *) arg;
      |          ^~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:11:51: error: invalid use of incomplete type ‘struct mocapNETWorkerThread(void*)::threadContext’
   11 |   struct mocapNETContext * ctx = &contextArray[ptr->threadID];
      |                                                   ^~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:8:10: note: forward declaration of ‘struct mocapNETWorkerThread(void*)::threadContext’
    8 |   struct threadContext * ptr = (struct threadContext *) arg;
      |          ^~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:24:3: error: ‘threadpoolWorkerInitialWait’ was not declared in this scope
   24 |   threadpoolWorkerInitialWait(ptr);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:26:10: error: ‘threadpoolWorkerLoopCondition’ was not declared in this scope
   26 |   while (threadpoolWorkerLoopCondition(ptr))
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:28:16: error: invalid use of incomplete type ‘struct mocapNETWorkerThread(void*)::threadContext’
   28 |     switch (ptr->threadID)
      |                ^~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:8:10: note: forward declaration of ‘struct mocapNETWorkerThread(void*)::threadContext’
    8 |   struct threadContext * ptr = (struct threadContext *) arg;
      |          ^~~~~~~~~~~~~
/home/tm/Downloads/MocapNET-master/src/MocapNET2/MocapNETLib2/core/multiThreaded.cpp:59:5: error: ‘threadpoolWorkerLoopEnd’ was not declared in this scope
   59 |     threadpoolWorkerLoopEnd(ptr);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/build.make:89: src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/core/multiThreaded.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:409: src/MocapNET2/MocapNETLib2/CMakeFiles/MocapNETLib2.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
tm@tm-VirtualBox:~/Downloads/MocapNET-master$

**Comment by AmmarkoV** [comment]
Hello the problem is that apparently you don't have git installed..!

```
./initialize.sh: line 285: git: command not found
```
I guess to get the software you download the zip/tar files from github which makes your installation needlessly difficult and harder to update!

Instead try 
```
sudo apt-get install git
```

 "cd"  to a directory which you plan on having your code ( for example Documents ) and then you can 
```
cd ~/Documents/
git clone https://github.com/FORTH-ModelBasedTracker/MocapNET
cd MocapNET
./initialize.sh
```
This will not only take care of the build dependencies etc, you will also be able to update by issuing 

```
./update.sh
```

In order to setup the repository I would expect that one uses git so thats why I had no check of it in the initialize script, however I added it now..

Regardless, I have updated the README and initialize.sh to make sure that git is installed

**Comment by Aurosutru** [comment]
After installing git and changing the repo download from the .zip file provided by Github to the cloned version this build was successful.  The program runs great, complete with graphics.  It's time to start testing, after finishing up issue #48.

**Comment by AmmarkoV** [comment]
Great! :)
