### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by PrashantSaikia** [FORTH-ModelBasedTracker/MocapNET#53]
When I run `./initialize.sh`, I get this error at some point after the Tensorflow installation:

```
[ 11%] Linking C executable ../../../GroundTruthDumper
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../GroundTruthDumper] Error 1
make[1]: *** [src/GroundTruthGenerator/CMakeFiles/GroundTruthDumper.dir/all] Error 2
make: *** [all] Error 2
```

What is this, and how do I fix it?

**Comment by AmmarkoV** [comment]
Hello, apparently clang doesn't like the  `rt` in this file.. 

```
target_link_libraries(GroundTruthDumper rt m pthread ) 
```

https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/GroundTruthGenerator/CMakeLists.txt#L13

I use gcc to compile the project and haven't tried clang!

**Comment by AmmarkoV** [comment]
As stated in my previous message  building with [CLANG](http://clang.org/) is not supported 
The underlying code is pretty vanilla C and C++ and should compile and link correctly with any sane compiler however there are apparently many differences with GCC in things like the RT library ( https://stackoverflow.com/questions/15821663/what-is-the-lrt-flag-in-gnu-make ). 
Unfortunately I don't have the resources to also support CLANG so this will not get fixed and I will have to close the issue..

Ammar
