### ISSUE TITLE
the given bvh file's result seem bad

### ISSUE THREAD

**Issue by visonpon** [FORTH-ModelBasedTracker/MocapNET#56]
Hi, I have download the provided bvh file of your demo, but it seems the reuslts are bad since the pose sometimes not right and the root motion has big problems like drifting and jitter. I wonder if this is the bvh file's problem or the model's ability not so well

**Comment by AmmarkoV** [comment]
Hello, this is real-time 3D pose estimation from a monocular RGB video in Youtube, with no provided calibration, no body dimensions on the tracked subject, with motion blur and a moving camera  ( as seen here  -> https://www.youtube.com/watch?v=GtJct8nKjcc#t=29s ) 
The BVH output is standard so I don't know what could go wrong with it, the ensemble and HCD fine-tuning is doing its best to accommodate the above challenges. This [paper](http://users.ics.forth.gr/~argyros/mypapers/2019_09_BMVC_mocapnet.pdf) describes exactly what is happening under the hood

**Comment by visonpon** [comment]
Hello, I have built the environment and went through the process to produce bvh file on my own video[with fixed camera position and high resolution], it seems the model has a limited ability on custom video. 
Nonetheless, this work still inspires me to do some work based on this, thanks~

**Comment by AmmarkoV** [comment]
Some tips for better I/O
A) It is important for the input video resolution to be close to the training  16:9
The "best" input videos are from GoPro cameras using a 1920x1080 resolution

B) If you are using the WebcamLiveDemo it uses a homebrewed 2d estimator that is not very accurate if you use --openpose you can use a "heavier" 2D joint estimator that is slightly better

C) for even better results I personally use a standalone OpenPose installation and dump .json files that I then convert to .csv files
A user has contributed this guide https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/doc/OpenPose.md that might be helpful for this 

in the next version I will add a MediaPipe binding to improve accuracy/performance and phase out my 2D estimator

**Comment by AmmarkoV** [comment]
The mediapipe wrapper is underway here : https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/src/python/mediapipe although not it is not yet functional..
