### ISSUE TITLE
strcasecmp_sk(skel->skeletonHeader[i].str,"visible_rfoot")!=0

### ISSUE THREAD

**Issue by youngallien** [FORTH-ModelBasedTracker/MocapNET#57]
int areFeetMissing(struct skeletonSerialized * skel)
{
    unsigned int activeJoints=0;
    for (unsigned int i=0; i<skel->skeletonBodyElements; i++)
    {
                if ( strcasecmp_sk(skel->skeletonHeader[i].str,"visible_rfoot")!=0)  { if (skel->skeletonBody[i].value) { ++activeJoints; }  }   
                if ( strcasecmp_sk(skel->skeletonHeader[i].str,"visible_rknee")!=0)  { if (skel->skeletonBody[i].value) { ++activeJoints; }  }   
                if ( strcasecmp_sk(skel->skeletonHeader[i].str,"visible_lfoot")!=0)  { if (skel->skeletonBody[i].value) { ++activeJoints; }  }   
                if ( strcasecmp_sk(skel->skeletonHeader[i].str,"visible_lknee")!=0)  { if (skel->skeletonBody[i].value) { ++activeJoints; }  } 
    }
    
    if (activeJoints<3) 
    {
 
      fprintf(stderr,YELLOW "Feet are missing, Only %u leg joints detected..\n" NORMAL,activeJoints);
      return 1; 
    }
    
    return 0;
}

I think it should be "==" rather than "!=" .

**Comment by AmmarkoV** [comment]
Hello you are right, it is a string check and strings are equal when the strcmp returns 0
