### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by shaheen69-wq** [FORTH-ModelBasedTracker/MocapNET#59]
SSE2 detected and will be used..
Using locally found libtensorflow v1 C-API
BVH Code found and will be used..
OpenGL support will not be compiled in
OpenCV code found and will be used..
/usr/share/OpenCV
-- Configuring done
CMake Error at src/MocapNET2/MocapNETLib2/CMakeLists.txt:14 (add_library):
  Cannot find source file:

    ../../Tensorflow/tensorflow.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at src/JointEstimator2D/CMakeLists.txt:11 (add_library):
  Cannot find source file:

    ../Tensorflow/tensorflow.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: MocapNETLib2
CMake Error: Cannot determine link language for target "MocapNETLib2".
CMake Error: CMake can not determine linker language for target: JointEstimator2D
CMake Error: Cannot determine link language for target "JointEstimator2D".
-- Generating done
-- Build files have been written to: /mnt/c/users/username/projects/MocapNET/build

**Comment by AmmarkoV** [comment]
Hello, it appears I have broken the TF1 compatibility and I have to repair the CMake script 

```
Using locally found libtensorflow v1 C-API
```

I think that if you remove the directory dependencies/libtensorflow and then rerun ./initialize.sh  to  switch to Tensorflow 2  -> https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L212  you should be able to compile normally as a workaround  (until I fix this!)

https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/src/Tensorflow

**Comment by AmmarkoV** [comment]
Hello, I might(?) have fixed it..!

Please try git pull and recompilation!

**Comment by shaheen69-wq** [comment]
Thank you for providing the solution, i fixed the problem

**Comment by shaheen69-wq** [comment]
But I encountered an error when trying to convert keypoints openpose to bvh after using the command ./MocapNET2CSV --from BRUout/2dJoints_v1.4.csv --size 640 480 
./MocapNET2CSV --from BRUout/2dJoints_v1.4.csv --size 640 480
2021-07-03 23:04:16.711701: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-07-03 23:04:16.713621: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
CPU :  Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
GPU :
Successfully opened CSV file BRUout/2dJoints_v1.4.csv
CSV file BRUout/2dJoints_v1.4.csv is now open
loadCalibration BRUout/ , color.calib
Reinforcing EN_US locale to force commas to dots (This warning appears only one time)
Failed @ loadCalibration BRUout/ , color.calib
Unable to init server: Could not connect: Connection refused

I have two graphics cards, but it only reads the built-in card, knowing that I activate the Nvidia card for everything

**Comment by shaheen69-wq** [comment]
Solved. For those who got the same error. parameter --novisualization is required.

**Comment by AmmarkoV** [comment]
Good to know!
the --novisualization basically deactivates all windows and is useful if you are using the software on Windows via the Linux Subsystem, if you are running it on Google Collab or if you are using it on a linux system via SSH or on a headless server!
