### ISSUE TITLE
The output bvh file dose not contains t pose and it is hard to use

### ISSUE THREAD

**Issue by he1016060110** [FORTH-ModelBasedTracker/MocapNET#62]
The output bvh file dose not contains t pose at the beginning and it is hard to use.

**Comment by AmmarkoV** [comment]
Hello!

By adding the commandline argument 

``` 
--tpose 

for example 

./MocapNET2LiveWebcamDemo --from /path/to/yourfile.mp4 --tpose

```
A T-Pose should be prepended to the BVH output..

As seen in the code [of the live webcam demo](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNET2LiveWebcamDemo/livedemo.cpp#L405) and the [CSV Demo](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETFromCSV/mocapnet2CSV.cpp#L330) and the simple [BVH writer code](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/bvh.cpp#L247)
