### ISSUE TITLE
Results Evaluation

### ISSUE THREAD

**Issue by KhalloufiHamza** [FORTH-ModelBasedTracker/MocapNET#65]
Hi,

I could not understand how did you compute the MPJPE while we have 3d coordinates in the form of Euler angles (in the BVH file), therefore we should use MPJAE for the angles. Did you convert the outcomes to another coordinates system? 
Could you please give the script that you used to compute the MPJPE for two BVH files?

Thank you

**Comment by AmmarkoV** [comment]
Hello, you can create a virtual camera and project a BVH solution to 2D or  3D coordinates..!
Check the function [convertBVHFrameToFlat3DPoints](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/bvh.cpp#L1424) and [convertBVHFrameTo2DPoints](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/bvh.cpp#L1301) for the code that does this..!

if you use ./Mocapnet2LiveWebcamDemo .... your args here ... --savecsv3d 
the program will spit out a .CSV file with the 3D locations..

I have also included the [python utility I wrote to compare between H36M MPJPE and my output here](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py)
