### ISSUE TITLE
KV260 AI starterkit to build mocap

### ISSUE THREAD

**Issue by AmmarkoV** [FORTH-ModelBasedTracker/MocapNET#70]
@AmmarkoV Hi,I'm a undergratuate from China and I have attended the Adaptive Computing Challenge 2021
with Xilinx and I want to use the KV260 AI starterkit to make a mocap which Iead me to find your project，I can‘t install your MocapNET directly using the initialize.sh script which shown in this picture:
![image](https://user-images.githubusercontent.com/53631206/151365907-f186491a-8c3c-4211-b697-a8e5d4691bb7.png)
I'm not sure if it is caused by the architecture of KV260，I checked the shell script and found it was mainly download some pretrained model and configure the environment of the platform.And the xilinx's vitis-ai repository have intergrated the openpose model,So I want to ask you how you finally generate the BVH files through MocapNET and I wonder if I can use the openpose model in the vitis library to achieve it too,I would appreciate it if you can give a reply:-)

_Originally posted by @Hezhexi2002 in https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/55#issuecomment-1023204934_

**Comment by AmmarkoV** [comment]
Hello!

I am not familiar with the KV260 architecture, however from what I am seeing from its website ( https://www.xilinx.com/products/som/kria/kv260-vision-starter-kit.html ) this is a device that departs from the x86/x64 architecture that MocapNET was developed for.. 

I think that porting MocapNET to this architecture is going to be difficult..! 

To achieve it you will need to build 3 things :

1)  The [libtensorflow compiled for C](https://www.tensorflow.org/install/lang_c)  , you will have to be able [to compile a libtensorflow library for the particular architecture](https://www.tensorflow.org/install/source), given that tensorflow uses the weird and non-standard bazel build system I seriously doubt that this will work.. My code has a [Tensorflow 1](https://www.xilinx.com/products/som/kria/kv260-vision-starter-kit.html)/[Tensorflow 2](https://www.xilinx.com/products/som/kria/kv260-vision-starter-kit.html)  wrapper to use Tensorflow as the Neural Network framework..

2) [OpenCV](https://opencv.org/releases/) should be also be built from scratch if you are using a non-standard arch, this is used for the visual output and graphics

3) The rest of my code is vanilla C / C++ so it "should" compile using CMake given any GCC 

If any one of this things does not build properly because of problem with the KV260 architecture then the whole thing wont work.. 

Now what you sent me on the screenshot is actually a problem parsing the ./initialize.sh script!
It appears for whatever reason that the bash program on your KV260 machine gets stuck on some  '\r' characters in https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh ..!

I don't know why, initialize.sh is a simple text file written using the standard Linux encoding so I don't know why the KV260 bash would fail to parse it.. :(

To help more you should first find out why the bash script is not properly executing, [googling the issue has some hints](https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile)..

**Comment by nowhereman1999** [comment]
@AmmarkoV Thanks for your detailed answer，I'm so sorry to reply you so late until now because I haven't came back to school yet.It is really difficult to run mocap on KV260 due to the architecture of it，I will try to install all the dependcies you have mentioned above as soon as I go back to school，your patience moved me so deeply that I want to apologize for 
this late reply again and hope you will not mind it！：-)

**Comment by AmmarkoV** [comment]
No problem !

**Comment by nowhereman1999** [comment]
> No problem !

![image](https://user-images.githubusercontent.com/53631206/157216351-39e08b5c-0bfc-4e09-b9ec-aa40455b4181.png)
Hi ,as you can see,now I can run the initialize.sh with no error.The reason why it didn't work before is because the script is written in windows which ends with \r\n but in unix it end with \n,so the problem was solved after I changed file format.I'm really exited to tell you about this and I will report you more informations about my process!：-）

**Comment by nowhereman1999** [comment]
@AmmarkoV Hi,sorry to bother you again,but now I meet the new error when it began to make:
![image](https://user-images.githubusercontent.com/53631206/157227798-aa744043-28bb-48e1-bb11-3a12420a941f.png)
It seems due to the source code but I can't find the cpp file in the src folder,could you please tell me what causes it?

**Comment by AmmarkoV** [comment]
Hello , try running the ./update.sh script in the root directory,
or
cd dependencies/RGBDAcquisition
git pull

and then rerunning the make command

I think this might be caused  by mismatched MocapNET/RGBDAcquisition versions !
Sorry it took so long to answer you, the issue has been open for very long and I failed to notice that there was a new message in it!

**Comment by nowhereman1999** [comment]
> Hello , try running the ./update.sh script in the root directory,
> or
> cd dependencies/RGBDAcquisition
> git pull
> 
> and then rerunning the make command
> 
> I think this might be caused  by mismatched MocapNET/RGBDAcquisition versions !
> Sorry it took so long to answer you, the issue has been open for very long and I failed to notice that there was a new message in it!
> 

ok，thank you for your sincere reply，I will try the way you suggested tomorrow and then I will give you a feedback.

**Comment by nowhereman1999** [comment]
Sorry to bother you again,I'd like to inform you in advance that I may use the code from your repo to complete the e Adaptive Computing Challenge 2021 with Xilinx but I'll definitely cite your work in my  project.So I want to ask you wether I can gain your permission to do this?

**Comment by nowhereman1999** [comment]
> Hello , try running the ./update.sh script in the root directory, or cd dependencies/RGBDAcquisition git pull
> 
> and then rerunning the make command
> 
> I think this might be caused by mismatched MocapNET/RGBDAcquisition versions ! Sorry it took so long to answer you, the issue has been open for very long and I failed to notice that there was a new message in it!

![image](https://user-images.githubusercontent.com/53631206/159119969-84f60c53-a112-445b-97a9-b2c3af366682.png)
It occurs another error which is shown in the picture above after I follow your suggestions,so how can I solve this?

**Comment by nowhereman1999** [comment]
@AmmarkoV Hi,I checked some closed issues have been mentioned under your repo,I found that there is a issue which is similar to my problem:https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/20.The guy wanted to install the Mocap on Jeston which is also a ARM device and you pointed the error is due to the tensorflow lib,to solve that you must install the precompiled tensorflow for ARM or recompiled it from the source code which is not surpported by google.So I'm wondering if my error is caused by it too？

**Comment by AmmarkoV** [comment]
> Sorry to bother you again,I'd like to inform you in advance that I may use the code from your repo to complete the e Adaptive Computing Challenge 2021 with Xilinx but I'll definitely cite your work in my project.So I want to ask you wether I can gain your permission to do this?

Hello it is ok to use the code for research purposes, or this contest however using the code for a commercial application needs special permissions from the[ Foundation of Research Department](https://forth.gr/en/home/) which legally owns the copyright of the code. See the [license.txt ](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/license.txt) for more information. 


> mentioned under your repo,I found that there is a issue which is similar to my problem:#20 guy wanted to install the Mocap on Jeston which is also a ARM device and you pointed the error is due to the tensorflow lib
It is true that in an ARM device you will need a tensorflow for ARM build in order for it to work 

again the missing JSON file is references in Line 137 of the central CMakeLists.txt
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/CMakeLists.txt#L137

is part of the RGBDAcquisition project :
https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/bvh_to_json.c#L375

This compilation error again looks like there is something wrong with the versions. 
It appears that you updated the RGBDAcquisition but now the MocapNET code is behind ..

Running the update.sh script should take care of it 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/update.sh

While being in the root directory run :  
`./update.sh`

**Comment by nowhereman1999** [comment]
emmm，I have run the update.sh and then it throw this error again so did you mean that I need to run it again？

**Comment by AmmarkoV** [comment]
Unfortunately yes, you need to check if your CMakeLists.txt looks like this :  
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/CMakeLists.txt#L137
and
if the dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/ has  the bvh_to_json.c file !
 
https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/bvh_to_json.c#L375

**Comment by nowhereman1999** [comment]
> Unfortunately yes, you need to check if your CMakeLists.txt looks like this :  
> https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/CMakeLists.txt#L137
> and
> if the dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/ has  the bvh_to_json.c file !
>  
> https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/bvh_to_json.c#L375

ok，I will check it tomorrow because it is midnight right now so honestly I'm a little bit of tired and I want to go to sleep，but thank for your patience again！：-)

**Comment by AmmarkoV** [comment]
Yeah I'll try to respond faster and sorry you are having troubles! and good luck with your competition!

**Comment by nowhereman1999** [comment]
> Unfortunately yes, you need to check if your CMakeLists.txt looks like this : https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/CMakeLists.txt#L137 and if the dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/ has the bvh_to_json.c file !
> 
> https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/bvh_to_json.c#L375

![image](https://user-images.githubusercontent.com/53631206/159151489-6404d59b-d6c2-4e31-9235-c7cd95c7d9df.png)
I have checked the directory and found that there is a bvh_to_json.c but the L137 of my CMaKeLists.txt is different from yours
![image](https://user-images.githubusercontent.com/53631206/159151624-d485890d-5e6a-468e-9279-eb2aa5a810db.png)
so is this causing my error and if it is what should I do to solve it?

**Comment by AmmarkoV** [comment]
it should be the case that when you 
`git pull origin master` CMake will update the CMakeLists.txt with the version in the repository 
If this does not happen there is some problem with git and your cloned copy of the repository probably..

The easiest way to fix it is to manually is to copy paste the missing 
`${CMAKE_SOURCE_DIR}/dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/export/bvh_to_json.c
`
to your CMakeLists.txt file however the question remains why this is not updating automatically :S which I have no idea why

**Comment by AmmarkoV** [comment]
also make sure you are using the master or mnet3 branch by doing 
`git checkout master` in case you are using another branch

**Comment by Hezhexi2002** [comment]
> also make sure you are using the master or mnet3 branch by doing 
> `git checkout master` in case you are using another branch

oh I get it，I just found that I was using the master branch and now I will switch to the mnet3 branch to try it again！

**Comment by nowhereman1999** [comment]
ok,I see and I have cloned the repo once again and run the initialize.sh again which has not thrown a error so far but I'm not sure if it will occur the same error during make.It will take a period of time to finish download the models so I might give you a response later.At the same time,I want to explain to you about my request of using your code in my project again.Actually the race finally requires me to submit my repo which include the code I used for the project,and here my repo's link:[https://github.com/Hezhexi2002/KV260-Mocap](url) which you can see I haven't put my code,so I'm not sure wether this is a commercial application and if it does I'll immediately stop using your code,you are a very kind and nice guy,I'll still say thank you if I can't use your code for your patience!:-)

**Comment by nowhereman1999** [comment]
@AmmarkoV I’m so sorry to tell you that I still get a similar error like this:
![image](https://user-images.githubusercontent.com/53631206/159192039-14880a1a-25dc-4501-8cc6-cf6b8ea2676d.png)
and I'm sure that I'm using the master branch and I have no idea to deal with this,so how did it happen again?

**Comment by nowhereman1999** [comment]
![image](https://user-images.githubusercontent.com/53631206/159193216-5a3b0766-ab6f-4574-91c0-f520cc597c1c.png)
Hi,I ran the initialize.sh again and it seems like working this time but still throw this error,However,I believe this is due to the tensorflow lib I installed,so did you have a tensorflow lib build for ARM device or where I can find a pre-compiled lib for ARM?

**Comment by AmmarkoV** [comment]
also make sure you are using the master or mnet3 branch by doing 
`git checkout master` in case you are using another branch

> @AmmarkoV I’m so sorry to tell you that I still get a similar error like this: ![image](https://user-images.githubusercontent.com/53631206/159192039-14880a1a-25dc-4501-8cc6-cf6b8ea2676d.png) and I'm sure that I'm using the master branch and I have no idea to deal with this,so how did it happen again?

Hello so once again this is this file : 
https://github.com/AmmarkoV/RGBDAcquisition/blob/master/tools/PThreadWorkerPool/pthreadWorkerPool.h

which should be located at `dependencies/RGBDAcquisition/tools/PThreadWorkerPool/pthreadWorkerPool.h `
I don't know why it would be missing although since you manually create a different repository any new file added needs mirroring when this happens

**Comment by AmmarkoV** [comment]
> ![image](https://user-images.githubusercontent.com/53631206/159193216-5a3b0766-ab6f-4574-91c0-f520cc597c1c.png) Hi,I ran the initialize.sh again and it seems like working this time but still throw this error,However,I believe this is due to the tensorflow lib I installed,so did you have a tensorflow lib build for ARM device or where I can find a pre-compiled lib for ARM?

Yes this error means that CMake did not detect a tensorflow library so it can't find the libtensorflow.so library or actually that it did but the tensorflow lib provided is in the wrong format ( x64 ) instead of ARM

**Comment by nowhereman1999** [comment]
@AmmarkoV Hi I'm very excited to tell you that I have successfully compiled it in my KV260 since I found a precompiled libtensorflow.so for jetson nano from this link:[https://github.com/nevillerichards/tensorflow/releases](url) and it also works for KV260,I guess the reason for that is both of them are ARM device and their cpu are both belonged to Cotex A series.Anyway,I finally install MocapNET in KV260 and I'll test the performance of it but I thought it will not be so well because I didn't use the DPU of KV260 to accelerate the model which I probably work on in the future.
![image](https://user-images.githubusercontent.com/53631206/159403221-d8488c99-577f-489a-80a4-41b515ab005a.png)

**Comment by AmmarkoV** [comment]
Nice :) Good luck!

**Comment by nowhereman1999** [comment]
> Nice :) Good luck!

I'm so sorry to bother you again,but it seems to appear another error again,I can run the opencvtest with my usb camera properly like this:
![image](https://user-images.githubusercontent.com/53631206/159624450-fc8b3560-2629-419f-b1d7-1849eb2528b0.png)
However,the fps when I run the livedemo using my usbcamera is so low which is only 0.83 FPS like this:
![image](https://user-images.githubusercontent.com/53631206/159625217-9ff27caf-cf7a-4a08-ba8f-e313b86202a1.png)
I'm wondering if it caused by the compute capability limitations of the cortex-a53 and how can I accelerate it？
