### ISSUE TITLE
CSV from Openpose full of 0

### ISSUE THREAD

**Issue by heez77** [FORTH-ModelBasedTracker/MocapNET#75]
Hello, I have used the command lines you gave to use OpenPose 2D keypoints in order to get the BVH file. When converting my json file to a csv file, I noticed that the CSV file is filled with zeros in all the CSV.

Branch cloned : master
Linux Ubuntu 20.04

**Comment by AmmarkoV** [comment]
Hello!
Can you give me more details on the commands you execute ?

**Comment by AmmarkoV** [comment]
Hello, 
I cannot replicate your issue so closing this issue
