### ISSUE TITLE
switch --novisualization keeps the program in dead loop

### ISSUE THREAD

**Issue by VisImage** [FORTH-ModelBasedTracker/MocapNET#80]
What is actually happens. 

"./MocapNET2LiveWebcamDemo --from shuffle.webm --novisualization --frames 10" still keeps running after over 5 minutes.

"./MocapNET2LiveWebcamDemo --from shuffle.webm --frames 10" takes about 10 seconds to complete

**Comment by AmmarkoV** [comment]
Hello, thanks for reporting this will check it out..

**Comment by AmmarkoV** [comment]
Fixed, the frame incrementation happened inside an if statement that only got triggered if visualization was enabled..!
It is quite silly actually!
Thanks for reporting this! Waiting for confirmation that it works for you!

**Comment by VisImage** [comment]
Great, Ammar ! It works now.  Tested on both Ubuntu and Windwos/WSL, using  switch --novisualization.

We'll evaluate the performance in near future, and can report to you if interested. Do you have any reference to BVH file used?  How are the (openpose) keypoints linked with (BVH) joints?

Thank you.

Peter

**Comment by VisImage** [comment]
closed by accidentally.

**Comment by AmmarkoV** [comment]
These are the name arrays : 
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/commonSkeleton.hpp

and these are the BVH joints
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/dataset/headerWithHeadAndOneMotion.bvh

**Comment by AmmarkoV** [comment]
Since the main issue is fixed I am closing this, if you have a new question/issue/bug feel free to open a new one to keep searches of problems relevant to the Issue titles
