### ISSUE TITLE
Problem with generating BVH file using images that only show the torso

### ISSUE THREAD

**Issue by tasinislam21** [FORTH-ModelBasedTracker/MocapNET#82]
Hi,

I have a problem with the BVH file produced by this repository. I am working with images that only show the upper body. Whilst the poses are detected on the RGB image, the posture does not reflect the same way on the BVH file. The screenshot below shows the difference. One would expect to see the right arm crossing over the left. 

![Publication1](https://user-images.githubusercontent.com/33097868/164456747-17955fb5-4b98-44bd-b631-7486b36375e8.jpg)

The only change I made to the code is that I have removed the if statement on line 255 of the livedemo.cpp because I do not need the lower body. 

What suggestion can you give me?

Thanks

**Comment by AmmarkoV** [comment]
Hello, unfortunately the 2D inputs given create a very under-constrained problem to solve which the MocapNET NN tries its best to explain.

If you rotate the blender BVH skeleton you can understand how assuming a side view for example the NN BVH solution approximates the input 2D points

For example although when looking this skeleton ( which I created to illustrate the ill-posed nature of 2D->3D  )  from the front it does not resemble this image

![screen-2022-04-25-22-53-40](https://user-images.githubusercontent.com/97630/165164649-00b7a428-3076-4848-ad17-998149307806.jpg)

if you rotate it

![screen-2022-04-25-22-53-56](https://user-images.githubusercontent.com/97630/165164671-f6e2f1d1-47e0-4342-9447-d479fe533fed.jpg)

and rotate it some more you can see how the hand configurations for example could be more similar

![screen-2022-04-25-22-53-50](https://user-images.githubusercontent.com/97630/165164681-7760ee5f-c502-472e-a381-51391e4fc5e8.jpg)

So I think the problem with this input is that the same 2D points can correspond to many 3D poses and this is why if you get poses with not very "unique limb" configurations there are a lot of possible solutions and what the neural network returns  get might not be the best one.. :(
I am working on improving the accuracy of the network however unfortunately it is a really difficult and challenging problem

**Comment by tasinislam21** [comment]
No worries! Thanks for your explaination.
