### ISSUE TITLE
Compareutility bug + wrong MPJE values

### ISSUE THREAD

**Issue by KhalloufiHamza** [FORTH-ModelBasedTracker/MocapNET#85]
Hi,

I tried to compare two CSV files using the new version of [compareutility.py](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py) script but I get this bug:

Traceback (most recent call last):
  File "C:\Users\pc\Desktop\Untitled Folder\compareUtility\compareUtility.py", line 401, in <module>
    out=readCSVFile(output,1.0,outputDelim,0,0)
  File "C:\Users\pc\Desktop\Untitled Folder\compareUtility\compareUtility.py", line 249, in readCSVFile
    thisInput[i]=float(rowIn[i])
ValueError: could not convert string to float: '0.0,193.501205,-2.1,-9.005805,192.050644,-1.6,-13.5609,149.742172,-2.9,-17.068104,110.194,-9.1,3.781974,248.951767,-3.8,17.700209,246.28,-10.8,48.040253,246.28,-10.8,-3.782006,248.95,-3.8,-17.7,246.2807,-10.8,-48.040141,246.2807,-10.8,-3,253.171524,-6.9,-3,262.266602,-5.0,9.005801,192.050461,-1.6,13.560868,149.742249,-2.9,17.0683,110.194084,-9.1'

I tried with the oldest version of the script [compareutility.py](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py), and I did not get a bug but I am still thinking that the MPJE is not correct because I get just 1 mm as an error, I found it not logical especially when I change arbitrarily the values in my CSV output I get an error of 6 mm despite I make big values.
When I change the Scale from 1.0 to other values I still get the same MPJE.
Please find attached the ground truth and the output.

https://drive.google.com/file/d/10bsaZIaSOr-kQaWvFUzDQIFFix5SAsEi/view?usp=sharing

Thanks,
Hamza Khalloufi

**Comment by AmmarkoV** [comment]
Hello I will look into this,
Thanks for reporting this!

**Comment by AmmarkoV** [comment]
Hello [procrustes analysis](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/align2DPoints.py#L16)  is scale invariant so changing the scale should not influence MPJE!
