### ISSUE TITLE
how to rigging vrm / live2d / normal video  with the  BVH outputs

### ISSUE THREAD

**Issue by yslion** [FORTH-ModelBasedTracker/MocapNET#86]
how to rigging vrm / live2d / normal video  with the  BVH outputs

**Comment by AmmarkoV** [comment]
Hello sorry for the very long delay responding to your message! 
I use [Makehuman](http://www.makehumancommunity.org/) plus this [Rig](http://www.makehumancommunity.org/content/cmu_plus_face.html)  plus The [BVH Retargetter](https://diffeomorphic.blogspot.com/p/bvh-retargeter.html) plugin for blender to do an "animation" with the BVH outputs and a rigged skinned human model!

**Comment by AmmarkoV** [comment]
I have added this video that explains how MocapNET output can be rigged and in integrated in Blender
[![YouTube Link](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/blenderytb.png)](https://www.youtube.com/watch?v=ooLRUS5j4AI)
