### ISSUE TITLE
send bvh data to blender or ue4 to drive human skeleton?

### ISSUE THREAD

**Issue by luoww1992** [FORTH-ModelBasedTracker/MocapNET#88]
i notice that you say  you can converte to BVH motion frames from video in real-time, and can use it in blender,
 i want to send bvh mocap data to blender to drive  human skeleton  in real-time.
so:
   step1 -- i get  bvh motion frame data by video frame one by one. 
    step2-- send the data to blender 
    step3-- blender analysis the bvh mocap data and to drive the skeleton.

now step1, and step2 is ok,
step3 for help.  
*******
it is better if we can send the data to ue4 to drive skeleton. 
can you give me some advience ?

**Comment by AmmarkoV** [comment]
Hello sorry for the very long delay! 
I use [Makehuman](http://www.makehumancommunity.org/) plus this [Rig](http://www.makehumancommunity.org/content/cmu_plus_face.html)  plus The [BVH Retargetter](https://diffeomorphic.blogspot.com/p/bvh-retargeter.html) plugin for blender.
Unfortunately I have never used unreal engine so I am not familiar with it!
Do you have a BVH skeleton or animation file that is compatible with unreal engine so I may try to remap my BVH to it ?

**Comment by AmmarkoV** [comment]
This is a video explaining how to send bvh data to blender and drive a human skeleton
[![YouTube Link](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/blenderytb.png)](https://www.youtube.com/watch?v=ooLRUS5j4AI)
