### ISSUE TITLE
Does it has to be full body to track?

### ISSUE THREAD

**Issue by daqjjang** [FORTH-ModelBasedTracker/MocapNET#89]
I tried to use videos with the upper body, but it seems that MocapNET does not work.
Is there any option for it?

**Comment by AmmarkoV** [comment]
Hello, 
No the tracker can work on upperbody only as seen here :  

[![YouTube Link](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/blenderytb.png)](https://www.youtube.com/watch?v=ooLRUS5j4AI)
