### ISSUE TITLE
How to convert 3d pose to quaternions or rotation matrix?

### ISSUE THREAD

**Issue by Joyako** [FORTH-ModelBasedTracker/MocapNET#90]

**Comment by AmmarkoV** [comment]
Hello, I have written from scratch a BVH reading/writing utility you can find on the [GroundTruthDumper](https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/src/GroundTruthGenerator) part of this repository.

This internally uses a different repo of mine which is called RGBDAcquisition.

To see the rotation matrices check the [bvh_printBVHTransform function](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/calculate/bvh_transform.c#L239)

To see the code that actually creates the rotation matrices for the different rotation orders etc check [this part of the repository](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/tools/AmMatrix/matrix4x4Tools.c#L717)
