### ISSUE TITLE
Please Clarify Commercial Use Price

### ISSUE THREAD

**Issue by Hunanbean-Collective** [FORTH-ModelBasedTracker/MocapNET#93]
I have been unable to determine if this can be used free commercially. I know that if OpenPose is used, they want $25,000 per year. But, aside from that, i cannot tell.

Simply put, is this free for commercial use?

Thank you

**Comment by AmmarkoV** [comment]
As mentioned in the [license.txt](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/license.txt) 
This codebase is free for for "personal" research and/or academic, non-profit, non-commercial use.

This work has been developed with funding from the [Foundation of Research And Technology Greece](https://www.forth.gr/en/home/) so they own its copyright and decide for its commercial price. So  for commercial use you should contact professor Antonis Argyros  ( his mail is  : argyros @ ics.forth.gr ).

**Comment by AmmarkoV** [comment]
Also as a side note and in regards to the 25.000$ of Openpose.  The "Openpose" network bundled in the "LiveWebcamDemo" samples does not use any of the code of the original [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) repository, it is trained from scratch, it just uses the "network configuration" of OpenPose and thus is named as such.  

That being said if someone wants he can use the original OpenPose network and then parse its JSON output using MocapNET, 

or 

One can use the [mediapipe](https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/src/python/mediapipe)  2D dumper provide

or 

Use the bundled networks we provide that however are geared towards high framerate but are not so accurate..

This means that a commercial use of MocapNET does not necessarily entail paying royalties to OpenPose just to clarify this.

**Comment by Hunanbean-Collective** [comment]
Excellent summary and contact information.

thank you
p.s. I somehow entirely missed that in the license
