### ISSUE TITLE
cannot connect to cvrlcode.ics.forth.gr

### ISSUE THREAD

**Issue by Connorppeach** [FORTH-ModelBasedTracker/MocapNET#96]
Hi It appears that cvrlcode.ics.forth.gr is down is there anywhere else I can get the dataset

**Comment by AmmarkoV** [comment]
Hello, the network operations center of FORTH appears to have implemented a very strict firewall that currently prevents  machines that where supposed to be publicly accessible from being accessed outside of the internet. 

I am very sorry about the problem, I will contact the people responsible, however this might take a while..

**Comment by Ishihara-Masabumi** [comment]
I have the same problem.
The error message is as follows;

```
Do you want to download the CMU BVH datasets ? 
The download is approximately 1GB and uncompressed will take 4GB of disk space 
(You probably don't need this if you dont want to use the GenerateGroundTruth/CSVClusterPlot utility)

 (Y/N)?Y
Could not find MotionCapture
--2023-07-05 14:20:22--  http://cvrlcode.ics.forth.gr/web_share/mocapnet//CMUPlusHeadMotionCapture.zip
cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr) をDNSに問いあわせています... 139.91.185.61
cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80 に接続しています... 失敗しました: 接続がタイムアウトしました.
再試行しています。

--2023-07-05 14:22:33--  (試行: 2)  http://cvrlcode.ics.forth.gr/web_share/mocapnet//CMUPlusHeadMotionCapture.zip
cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80 に接続しています... 失敗しました: 接続がタイムアウトしました.
再試行しています。

--2023-07-05 14:24:45--  (試行: 3)  http://cvrlcode.ics.forth.gr/web_share/mocapnet//CMUPlusHeadMotionCapture.zip
cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80 に接続しています... 失敗しました: 接続がタイムアウトしました.
再試行しています。

--2023-07-05 14:26:59--  (試行: 4)  http://cvrlcode.ics.forth.gr/web_share/mocapnet//CMUPlusHeadMotionCapture.zip
cvrlcode.ics.forth.gr (cvrlcode.ics.forth.gr)|139.91.185.61|:80 に接続しています...```
Continuously three times still missed the connection.

**Comment by hamouniii** [comment]
I have also the same problem. Is there any way to solve it?

**Comment by AmmarkoV** [comment]
Hello, 
Once again I am terribly sorry, the network operation center of FORTH still hasn't resolved the server/firewall issues.. :(

As a workaround you can try to download all the pretrained NN model files from [here](https://drive.google.com/file/d/1GtmPWOpf3MzhqhqegaC8cS3_m3Drp6y3/view?usp=drive_link) 
 
Extract them in the root directory of the project should create the dataset/combinedModel/mocapnet2 subdirectory with all the models inside

OR
 
```
cd path/to/mocapnet/directory/here
wget -O allInOneMNET2RedistMirrorICPR2020.zip "drive.google.com/u/3/uc?id=1GtmPWOpf3MzhqhqegaC8cS3_m3Drp6y3&export=download&confirm=yes"
unzip allInOneMNET2RedistMirrorICPR2020.zip
```

I will still try to contact them again to resolve the hosting issues  so that there is no need for a workaround, however until then I hope that this works for you!

**Comment by AmmarkoV** [comment]
Although the problem with cvrlcode.ics.forth.gr continues to exist I have added a workaround to the initialize.sh script so that a google drive link is used for acquiring the models and needed files. I am leaving the issue open to make sure this works for you @Connorppeach  @Ishihara-Masabumi  @hamounTUK .

**Comment by AmmarkoV** [comment]
The NOC of FORTH has fixed the issue so cvrlcode.ics.forth.gr is  available again.
Not only  this but now there is a Google mirror as a failsafe backup so,  as a result I am closing this issue

**Comment by justinjohn0306** [comment]
> The NOC of FORTH has fixed the issue so cvrlcode.ics.forth.gr is available again. Not only this but now there is a Google mirror as a failsafe backup so, as a result I am closing this issue

looks like the gdrive zip doesn't contain the motioncapture files

**Comment by AmmarkoV** [comment]
@justinjohn0306  
> > The NOC of FORTH has fixed the issue so cvrlcode.ics.forth.gr is available again. Not only this but now there is a Google mirror as a failsafe backup so, as a result I am closing this issue
> 
> looks like the gdrive zip doesn't contain the motioncapture files

The links for the BVH files in the Google Drive :
https://drive.google.com/file/d/1Zt-MycqhMylfBUqgmW9sLBclNNxoNGqV/view?usp=drive_link

**Comment by justinjohn0306** [comment]
> @justinjohn0306
> 
> > > The NOC of FORTH has fixed the issue so cvrlcode.ics.forth.gr is available again. Not only this but now there is a Google mirror as a failsafe backup so, as a result I am closing this issue
> > 
> > 
> > looks like the gdrive zip doesn't contain the motioncapture files
> 
> The links for the BVH files in the Google Drive : https://drive.google.com/file/d/1Zt-MycqhMylfBUqgmW9sLBclNNxoNGqV/view?usp=drive_link

can you set the sharing link permission to ``everyone``? so that we can access it?

**Comment by AmmarkoV** [comment]
> > @justinjohn0306
> > > > The NOC of FORTH has fixed the issue so cvrlcode.ics.forth.gr is available again. Not only this but now there is a Google mirror as a failsafe backup so, as a result I am closing this issue
> > > 
> > > 
> > > looks like the gdrive zip doesn't contain the motioncapture files
> > 
> > 
> > The links for the BVH files in the Google Drive : https://drive.google.com/file/d/1Zt-MycqhMylfBUqgmW9sLBclNNxoNGqV/view?usp=drive_link
> 
> can you set the sharing link permission to `everyone`? so that we can access it?

Thanks for reporting this @justinjohn0306 .
I think permissions are  now set to public.. 
Please confirm!
